In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
arr1 = np.arange(0,11)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [3]:
arr1[0:5]

array([0, 1, 2, 3, 4])

In [4]:
arr1[3:6]                                                                                       

array([3, 4, 5])

In [5]:
arr1[3:8]=99 #broadcasting
arr1

array([ 0,  1,  2, 99, 99, 99, 99, 99,  8,  9, 10])

In [ ]:
slice = arr1[5:] #pointer/reference

In [7]:
slice

array([99, 99, 99,  8,  9, 10])

In [9]:
ar_cpy = arr1.copy()
ar_cpy

array([ 0,  1,  2, 99, 99, 99, 99, 99,  8,  9, 10])

In [10]:
arr1[10]

np.int64(10)

In [11]:
print(arr1[10])

10


In [12]:
arr1[:5]

array([ 0,  1,  2, 99, 99])

In [13]:
arr1[:]

array([ 0,  1,  2, 99, 99, 99, 99, 99,  8,  9, 10])

In [14]:
arr1[0:11:2]

array([ 0,  2, 99, 99,  8, 10])

In [15]:
arr1[::-1]

array([10,  9,  8, 99, 99, 99, 99, 99,  2,  1,  0])

In [21]:
arr2 = np.arange(0,6).reshape([2,3])

In [22]:
arr2

array([[0, 1, 2],
       [3, 4, 5]])

In [28]:
arr2[:,[1,2,2]]

array([[1, 2, 2],
       [4, 5, 5]])

In [30]:
arr3 = np.arange(0,35).reshape([7,5])

In [31]:
print(arr3)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]]


In [32]:
arr3[:,[1,3,4]]

array([[ 1,  3,  4],
       [ 6,  8,  9],
       [11, 13, 14],
       [16, 18, 19],
       [21, 23, 24],
       [26, 28, 29],
       [31, 33, 34]])

In [33]:
arr3[:2,1:]

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [34]:
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [35]:
arr3[5:, 3:]

array([[28, 29],
       [33, 34]])

In [36]:
arr3[4:, 2:]

array([[22, 23, 24],
       [27, 28, 29],
       [32, 33, 34]])

In [38]:
slice = arr3[4:,3:]

In [39]:
slice

array([[23, 24],
       [28, 29],
       [33, 34]])

In [42]:
slice = np.array([[100,100],
                [100,100],
                [100,100]])

In [43]:
slice

array([[100, 100],
       [100, 100],
       [100, 100]])

In [44]:
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [47]:
arr3[4:,3:] = np.array([[100,100],
                [100,100],
                [100,100]])

In [48]:
arr3

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22, 100, 100],
       [ 25,  26,  27, 100, 100],
       [ 30,  31,  32, 100, 100]])