In [1]:
import numpy as np
import pandas as pd

In [2]:
arr2 = np.arange(1,51).reshape(5,10)

In [3]:
arr2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [5]:
s = np.sum(arr2, axis=0)
s

array([105, 110, 115, 120, 125, 130, 135, 140, 145, 150])

In [6]:
np.sum(arr2, axis=1)

array([ 55, 155, 255, 355, 455])

In [7]:
arr3 = np.arange(1,25).reshape(4,3,2)
arr3

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

In [8]:
np.sum(arr3, axis=0)

array([[40, 44],
       [48, 52],
       [56, 60]])

In [9]:
np.sum(arr3, axis=1)

array([[ 9, 12],
       [27, 30],
       [45, 48],
       [63, 66]])

In [10]:
np.sum(arr3, axis=2)

array([[ 3,  7, 11],
       [15, 19, 23],
       [27, 31, 35],
       [39, 43, 47]])

In [11]:
arr3

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

In [14]:
#conditional selection

In [15]:
arr1 = np.arange(1,11).reshape(2,5)

In [16]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
result = arr1[arr1>7]
result

array([ 8,  9, 10])

In [18]:
boolean = arr1[:] > 6
boolean

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True]])

In [28]:
arr1[arr1[:] > 8]

array([ 9, 10])

In [29]:
#concatenation

In [45]:
arr12 = np.arange (10,20).reshape(2,5)

In [46]:
arr12

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [47]:
np.concatenate((arr1,arr12), axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [49]:
np.concatenate((arr1,arr12), axis=1)

array([[ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 15, 16, 17, 18, 19]])

In [50]:
np.concatenate((arr1, arr12))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])